import {
  genericFillTemplateDefinition,
  confluenceOverwritePageDefinition,
  credalCallCopilotDefinition,
  googlemapsValidateAddressDefinition,
  mathAddDefinition,
  mongoInsertMongoDocDefinition,
  slackSendMessageDefinition,
  slackGetChannelMessagesDefinition,
  snowflakeGetRowByFieldValueDefinition,
  zendeskCreateZendeskTicketDefinition,
  zendeskListZendeskTicketsDefinition,
  zendeskGetTicketDetailsDefinition,
  zendeskUpdateTicketStatusDefinition,
  zendeskAddCommentToTicketDefinition,
  zendeskAssignTicketDefinition,
  openstreetmapGetLatitudeLongitudeFromLocationDefinition,
  nwsGetForecastForLocationDefinition,
  jiraAssignJiraTicketDefinition,
  jiraCommentJiraTicketDefinition,
  jiraCreateJiraTicketDefinition,
  jiraGetJiraTicketDetailsDefinition,
  jiraGetJiraTicketHistoryDefinition,
  jiraUpdateJiraTicketDetailsDefinition,
  jiraUpdateJiraTicketStatusDefinition,
  googlemapsNearbysearchRestaurantsDefinition,
  firecrawlScrapeUrlDefinition,
  resendSendEmailDefinition,
  linkedinCreateShareLinkedinPostUrlDefinition,
  googleOauthCreateNewGoogleDocDefinition,
  xCreateShareXPostUrlDefinition,
  firecrawlScrapeTweetDataWithNitterDefinition,
  finnhubSymbolLookupDefinition,
  finnhubGetBasicFinancialsDefinition,
  confluenceFetchPageContentDefinition,
  snowflakeRunSnowflakeQueryDefinition,
  lookerEnableUserByEmailDefinition,
  googleOauthUpdateDocDefinition,
  googleOauthScheduleCalendarMeetingDefinition,
  googleOauthListCalendarsDefinition,
  googleOauthListCalendarEventsDefinition,
  googleOauthUpdateCalendarEventDefinition,
  googleOauthDeleteCalendarEventDefinition,
  googleOauthCreateSpreadsheetDefinition,
  googleOauthUpdateSpreadsheetDefinition,
  googleOauthCreatePresentationDefinition,
  googleOauthUpdatePresentationDefinition,
  googleOauthSearchDriveByKeywordsDefinition,
  googlemailSearchGmailMessagesDefinition,
  googlemailListGmailThreadsDefinition,
  googleOauthListGroupsDefinition,
  googleOauthGetGroupDefinition,
  googleOauthListGroupMembersDefinition,
  googleOauthHasGroupMemberDefinition,
  googleOauthAddGroupMemberDefinition,
  googleOauthDeleteGroupMemberDefinition,
  salesforceUpdateRecordDefinition,
  salesforceCreateCaseDefinition,
  salesforceGenerateSalesReportDefinition,
  salesforceGetRecordDefinition,
  salesforceGetSalesforceRecordsByQueryDefinition,
  microsoftMessageTeamsChatDefinition,
  microsoftMessageTeamsChannelDefinition,
  asanaCommentTaskDefinition,
  asanaCreateTaskDefinition,
  asanaUpdateTaskDefinition,
  asanaSearchTasksDefinition,
  githubCreateOrUpdateFileDefinition,
  githubCreateBranchDefinition,
  githubCreatePullRequestDefinition,
  microsoftUpdateSpreadsheetDefinition,
  microsoftUpdateDocumentDefinition,
  microsoftCreateDocumentDefinition,
  microsoftGetDocumentDefinition,
  salesforceFetchSalesforceSchemaByObjectDefinition,
  firecrawlDeepResearchDefinition,
  jiraGetJiraIssuesByQueryDefinition,
  githubListPullRequestsDefinition,
  salesforceCreateRecordDefinition,
  ashbyCreateNoteDefinition,
  ashbyGetCandidateInfoDefinition,
  ashbyListCandidatesDefinition,
  ashbyListCandidateNotesDefinition,
  ashbySearchCandidatesDefinition,
  ashbyCreateCandidateDefinition,
  ashbyUpdateCandidateDefinition,
  ashbyAddCandidateToProjectDefinition,
  bingGetTopNSearchResultUrlsDefinition,
  gongGetGongTranscriptsDefinition,
  kandjiGetFVRecoveryKeyForDeviceDefinition,
  asanaListAsanaTasksByProjectDefinition,
  notionSearchByTitleDefinition,
  asanaGetTasksDetailsDefinition,
  jamfGetJamfComputerInventoryDefinition,
  jamfGetJamfFileVaultRecoveryKeyDefinition,
} from "../actions/autogen/templates";
import type { ActionTemplate } from "../actions/parse";

export type ActionGroups = Record<string, { description: string; actions: ActionTemplate[] }>;

export const ACTION_GROUPS: ActionGroups = {
  GENERIC: {
    description: "Generic utility actions",
    actions: [genericFillTemplateDefinition],
  },
  ASANA: {
    description: "Actions for interacting with Asana",
    actions: [
      asanaCommentTaskDefinition,
      asanaCreateTaskDefinition,
      asanaUpdateTaskDefinition,
      asanaSearchTasksDefinition,
      asanaListAsanaTasksByProjectDefinition,
      asanaGetTasksDetailsDefinition,
    ],
  },
  SLACK_LIST_CONVERSATIONS: {
    description: "Actions for interacting with Slack",
    actions: [slackSendMessageDefinition, slackGetChannelMessagesDefinition],
  },
  CONFLUENCE: {
    description: "Action for interacting with Confluence",
    actions: [confluenceOverwritePageDefinition, confluenceFetchPageContentDefinition],
  },
  MATH_ADD: {
    description: "Action for adding two numbers",
    actions: [mathAddDefinition],
  },
  GOOGLE_MAPS: {
    description: "Action for interacting with Google Maps",
    actions: [googlemapsValidateAddressDefinition, googlemapsNearbysearchRestaurantsDefinition],
  },
  GOOGLE_DRIVE: {
    description: "Action for interacting with Google Drive",
    actions: [
      googleOauthCreateNewGoogleDocDefinition,
      googleOauthUpdateDocDefinition,
      googleOauthCreateSpreadsheetDefinition,
      googleOauthUpdateSpreadsheetDefinition,
      googleOauthCreatePresentationDefinition,
      googleOauthUpdatePresentationDefinition,
      googleOauthSearchDriveByKeywordsDefinition,
    ],
  },
  GOOGLE_CALENDAR: {
    description: "Actions for interacting with Google Calendar",
    actions: [
      googleOauthScheduleCalendarMeetingDefinition,
      googleOauthListCalendarsDefinition,
      googleOauthListCalendarEventsDefinition,
      googleOauthUpdateCalendarEventDefinition,
      googleOauthDeleteCalendarEventDefinition,
    ],
  },
  GMAIL: {
    description: "Actions for interacting with Gmail",
    actions: [googlemailSearchGmailMessagesDefinition, googlemailListGmailThreadsDefinition],
  },
  CREDAL_CALL_COPILOT: {
    description: "Action for calling a Credal Copilot",
    actions: [credalCallCopilotDefinition],
  },
  LINKEDIN_SHARE_POST: {
    description: "Action for creating a share post url on linkedin",
    actions: [linkedinCreateShareLinkedinPostUrlDefinition],
  },
  ZENDESK_ACTIONS: {
    description: "Actions for interacting with Zendesk",
    actions: [
      zendeskCreateZendeskTicketDefinition,
      zendeskListZendeskTicketsDefinition,
      zendeskGetTicketDetailsDefinition,
      zendeskUpdateTicketStatusDefinition,
      zendeskAddCommentToTicketDefinition,
      zendeskAssignTicketDefinition,
    ],
  },
  BING_SEARCH: {
    description: "Action for searching Bing",
    actions: [bingGetTopNSearchResultUrlsDefinition],
  },
  MONGO_INSERT_DOC: {
    description: "Action for inserting a document into a MongoDB collection",
    actions: [mongoInsertMongoDocDefinition],
  },
  SNOWFLAKE_ACTIONS: {
    description: "Action for getting content from a Snowflake table",
    actions: [snowflakeGetRowByFieldValueDefinition, snowflakeRunSnowflakeQueryDefinition],
  },
  JIRA_ACTIONS: {
    description: "Action for interacting with Jira tickets",
    actions: [
      jiraAssignJiraTicketDefinition,
      jiraCreateJiraTicketDefinition,
      jiraCommentJiraTicketDefinition,
      jiraGetJiraTicketDetailsDefinition,
      jiraGetJiraTicketHistoryDefinition,
      jiraUpdateJiraTicketDetailsDefinition,
      jiraUpdateJiraTicketStatusDefinition,
      jiraGetJiraIssuesByQueryDefinition,
    ],
  },
  OPENSTREETMAP_GET_LATITUDE_LONGITUDE_FROM_LOCATION: {
    description: "Action for getting the latitude and longitude of a location",
    actions: [openstreetmapGetLatitudeLongitudeFromLocationDefinition],
  },
  NWS_GET_FORECAST_FOR_LOCATION: {
    description: "Action for getting the weather forecast for a location",
    actions: [nwsGetForecastForLocationDefinition],
  },
  FIRECRAWL: {
    description: "Actions for interacting with Firecrawl",
    actions: [
      firecrawlScrapeUrlDefinition,
      firecrawlScrapeTweetDataWithNitterDefinition,
      firecrawlDeepResearchDefinition,
    ],
  },
  RESEND: {
    description: "Action for sending an email",
    actions: [resendSendEmailDefinition],
  },
  X: {
    description: "Actions for interacting with X(formerly twitter)",
    actions: [xCreateShareXPostUrlDefinition],
  },
  GONG: {
    description: "Actions for interacting with Gong",
    actions: [gongGetGongTranscriptsDefinition],
  },
  FINNHUB: {
    description: "Action for interacting with Finnhub for stock market data",
    actions: [finnhubSymbolLookupDefinition, finnhubGetBasicFinancialsDefinition],
  },
  JAMF: {
    description: "Actions for interacting with Jamf",
    actions: [jamfGetJamfComputerInventoryDefinition, jamfGetJamfFileVaultRecoveryKeyDefinition],
  },
  LOOKER: {
    description: "Actions for interacting with Looker",
    actions: [lookerEnableUserByEmailDefinition],
  },
  SALESFORCE: {
    description: "Actions for interacting with Salesforce",
    actions: [
      salesforceUpdateRecordDefinition,
      salesforceCreateRecordDefinition,
      salesforceCreateCaseDefinition,
      salesforceGenerateSalesReportDefinition,
      salesforceGetRecordDefinition,
      salesforceGetSalesforceRecordsByQueryDefinition,
      salesforceFetchSalesforceSchemaByObjectDefinition,
    ],
  },
  MICROSOFT: {
    description: "Actions for interacting with Microsoft 365",
    actions: [
      microsoftMessageTeamsChatDefinition,
      microsoftMessageTeamsChannelDefinition,
      microsoftUpdateSpreadsheetDefinition,
      microsoftUpdateDocumentDefinition,
      microsoftCreateDocumentDefinition,
      microsoftGetDocumentDefinition,
    ],
  },
  KANDJI: {
    description: "Actions for interacting with Kandji",
    actions: [kandjiGetFVRecoveryKeyForDeviceDefinition],
  },
  GITHUB: {
    description: "Actions for interacting with GitHub",
    actions: [
      githubCreateOrUpdateFileDefinition,
      githubCreateBranchDefinition,
      githubCreatePullRequestDefinition,
      githubListPullRequestsDefinition,
    ],
  },
  ASHBY: {
    description: "Actions for interacting with Ashby",
    actions: [
      ashbyCreateNoteDefinition,
      ashbyGetCandidateInfoDefinition,
      ashbyListCandidatesDefinition,
      ashbyListCandidateNotesDefinition,
      ashbySearchCandidatesDefinition,
      ashbyCreateCandidateDefinition,
      ashbyUpdateCandidateDefinition,
      ashbyAddCandidateToProjectDefinition,
    ],
  },
  NOTION: {
    description: "Actions for interacting with Notion",
    actions: [notionSearchByTitleDefinition],
  },
  GOOGLE_GROUPS: {
    description: "Google Workspace Groups management actions",
    actions: [
      googleOauthListGroupsDefinition,
      googleOauthGetGroupDefinition,
      googleOauthListGroupMembersDefinition,
      googleOauthHasGroupMemberDefinition,
      googleOauthAddGroupMemberDefinition,
      googleOauthDeleteGroupMemberDefinition,
    ],
  },
};
